- name: loops
  hosts: localhost
  tasks:
  - name: install or uninstall packages
    ansible.builtin.package:
      name: "{{item}}" # install multiple packages
      state: "{{item.state}}"
    loop:
    - {name: 'git' , state: 'present'}
    - {name: 'mysql' , state: 'absent'}


